"use client";

import React, { useState } from "react";
import {
    FileText,
    Target,
    Users,
    MessageSquare,
    Sparkles,
    ArrowRight,
    CheckCircle2,
    Loader2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useAppStore } from "@/store/useAppStore";
import { useT } from "@/lib/i18n";
import { cn } from "@/lib/utils";
import { exportConsultancyReport } from "@/lib/exporters";

interface WizardState {
    step: 1 | 2;
    audience: string;
    objective: string;
    context: string;
    isGenerating: boolean;
    report: string | null;
}

export function ConsultancyReportWizard() {
    const t = useT();
    const { dataset, datasetName, charts, transformations } = useAppStore();
    const [state, setState] = useState<WizardState>({
        step: 1,
        audience: "",
        objective: "",
        context: "",
        isGenerating: false,
        report: null
    });

    const audiences = [
        { id: 'executive', name: t('audExecutive'), icon: Users },
        { id: 'technical', name: t('audTechnical'), icon: Target },
        { id: 'general', name: t('audGeneral'), icon: MessageSquare }
    ];

    const objectives = [
        { id: 'risks', name: t('objRisks') },
        { id: 'opportunities', name: t('objOpportunities') },
        { id: 'governance', name: t('objGovernance') },
        { id: 'overview', name: t('objOverview') }
    ];

    const handleGenerate = async () => {
        setState(prev => ({ ...prev, isGenerating: true }));

        // Mock AI Call
        setTimeout(() => {
            const mockReport = `
# Executive Strategic Report: ${datasetName || 'Project Intelligence'}
**Date:** ${new Date().toLocaleDateString()}
**Audience:** ${state.audience.toUpperCase()}
**Strategic Focus:** ${state.objective.toUpperCase()}

## 1. Governance & Integrity
The dataset contains ${dataset?.length || 0} records across ${Object.keys(dataset?.[0] || {}).length} variables. 
Initial scanning identified ${transformations.length} data quality points which were successfully optimized through Neural Preprocessing. 
The current integrity score is **98.4%**, making it suitable for high-stakes decision making.

## 2. Exploratory Insights
Through multidimensional analysis, we identified ${charts.length} key patterns. 
Notably, the correlation between primary variables indicates a strong trend in ${state.objective === 'risks' ? 'operational risk' : 'efficiency gains'}.

## 3. Strategic Conclusions
- **Optimization:** Current data distribution suggests an immediate opportunity for resource reallocation.
- **Risk Mitigation:** Observed outliers in key indicators warrant a secondary audit of the operational flow.
- **Actionable Recommendation:** Based on the ${state.audience} perspective, we recommend an initial rollout of Phase 1 automation by Q3.

*Generated by DataFlow AI Consultant Suite*
            `;
            setState(prev => ({ ...prev, isGenerating: false, report: mockReport.trim(), step: 2 }));
        }, 1500);
    };

    if (!dataset) return null;

    return (
        <div className="w-full bg-white rounded-3xl border border-gray-100 shadow-xl overflow-hidden min-h-[500px] flex flex-col">
            {/* Header */}
            <div className="p-8 border-b border-gray-50 bg-gray-50/50">
                <div className="flex items-center gap-4 mb-2">
                    <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-white">
                        <Sparkles className="w-5 h-5 fill-current" />
                    </div>
                    <div>
                        <h2 className="text-xl font-black text-gray-900 tracking-tight">{t('strategyConsultant')}</h2>
                        <p className="text-[11px] font-black uppercase tracking-widest text-primary/60 italic">{t('enterpriseReportingEngine')}</p>
                    </div>
                </div>
            </div>

            <div className="p-8 flex-1 flex flex-col">
                <AnimatePresence mode="wait">
                    {state.step === 1 ? (
                        <motion.div
                            key="step1"
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: 20 }}
                            className="space-y-8"
                        >
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                                {/* Audience Selection */}
                                <div className="space-y-4">
                                    <label className="text-[10px] font-black uppercase tracking-wider text-gray-400">{t('targetAudience')}</label>
                                    <div className="grid grid-cols-1 gap-3">
                                        {audiences.map(aud => (
                                            <button
                                                key={aud.id}
                                                onClick={() => setState(s => ({ ...s, audience: aud.id }))}
                                                className={cn(
                                                    "flex items-center gap-4 p-4 rounded-2xl border transition-all text-left group",
                                                    state.audience === aud.id
                                                        ? "bg-primary border-primary text-white shadow-lg"
                                                        : "bg-white border-gray-100 text-gray-600 hover:border-primary/30"
                                                )}
                                            >
                                                <aud.icon className={cn("w-5 h-5", state.audience === aud.id ? "text-white" : "text-gray-400 group-hover:text-primary")} />
                                                <span className="font-bold text-sm">{aud.name}</span>
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                {/* Objective Selection */}
                                <div className="space-y-4">
                                    <label className="text-[10px] font-black uppercase tracking-wider text-gray-400">{t('strategicObjective')}</label>
                                    <div className="grid grid-cols-1 gap-3">
                                        {objectives.map(obj => (
                                            <button
                                                key={obj.id}
                                                onClick={() => setState(s => ({ ...s, objective: obj.id }))}
                                                className={cn(
                                                    "flex items-center justify-between p-4 rounded-2xl border transition-all text-left",
                                                    state.objective === obj.id
                                                        ? "bg-gray-900 border-gray-900 text-white shadow-lg"
                                                        : "bg-white border-gray-100 text-gray-600 hover:border-primary/30"
                                                )}
                                            >
                                                <span className="font-bold text-sm">{obj.name}</span>
                                                {state.objective === obj.id && <CheckCircle2 className="w-4 h-4 text-primary" />}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Additional Context */}
                            <div className="space-y-4 pt-4">
                                <label className="text-[10px] font-black uppercase tracking-wider text-gray-400 flex items-center gap-2">
                                    <MessageSquare className="w-3 h-3" /> {t('additionalStrategicContext')}
                                </label>
                                <textarea
                                    value={state.context}
                                    onChange={(e) => setState(s => ({ ...s, context: e.target.value }))}
                                    placeholder={t('contextPlaceholder')}
                                    className="w-full min-h-[120px] p-6 rounded-3xl bg-gray-50 border-gray-100 focus:bg-white focus:border-primary/30 transition-all outline-none text-sm font-medium text-gray-700 resize-none placeholder:text-gray-300 shadow-inner"
                                />
                            </div>

                            <button
                                disabled={!state.audience || !state.objective || state.isGenerating}
                                onClick={handleGenerate}
                                className={cn(
                                    "w-full py-5 rounded-3xl text-xs font-black uppercase tracking-[0.2em] transition-all flex items-center justify-center gap-4 active:scale-95 shadow-2xl",
                                    (!state.audience || !state.objective || state.isGenerating)
                                        ? "bg-gray-100 text-gray-400 cursor-not-allowed"
                                        : "bg-primary text-white hover:brightness-110"
                                )}
                            >
                                {state.isGenerating ? (
                                    <>
                                        <Loader2 className="w-5 h-5 animate-spin" />
                                        {t('analyzingDatasetGeneratingReport')}
                                    </>
                                ) : (
                                    <>
                                        {t('generateProfessionalReport')}
                                        <ArrowRight className="w-5 h-5" />
                                    </>
                                )}
                            </button>
                        </motion.div>
                    ) : (
                        <motion.div
                            key="step2"
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            className="space-y-10"
                        >
                            <div className="bg-gray-50/50 p-10 rounded-4xl border border-gray-100 font-serif leading-relaxed text-gray-800 whitespace-pre-wrap shadow-inner min-h-[400px]">
                                {state.report}
                            </div>

                            <div className="flex items-center gap-4">
                                <button
                                    onClick={() => setState(prev => ({ ...prev, step: 1, report: null }))}
                                    className="flex-1 py-5 rounded-3xl bg-white border border-gray-200 text-gray-500 text-xs font-black uppercase tracking-widest hover:bg-gray-50 transition-all"
                                >
                                    {t('refineContext')}
                                </button>
                                <button
                                    onClick={() => {
                                        if (state.report) {
                                            exportConsultancyReport({
                                                title: `Strategic Report: ${datasetName || 'Project'}`,
                                                content: state.report,
                                                audience: state.audience,
                                                objective: state.objective
                                            });
                                        }
                                    }}
                                    className="flex-1 py-5 rounded-3xl bg-gray-900 text-white text-xs font-black uppercase tracking-widest hover:brightness-125 transition-all shadow-xl flex items-center justify-center gap-3"
                                >
                                    <FileText className="w-4 h-4" />
                                    {t('exportAsPdf')}
                                </button>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
